import "./styles/barfiller.css";
import "./styles/bootstrap.min.css";
import "./styles/elegant-icons.css";
import "./styles/flaticon.css";
import "./styles/font-awesome.min.css";
import "./styles/magnific-popup.css"
import "./styles/nice-select.css";
// import "./styles/owl.carousel.min.css";
import "./styles/slicknav.min.css";
import "./styles/style.css";



import HeaderNav from "./components/header";

/* const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
 */

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={``}>
      <HeaderNav itemsInCart={0}/>
        {children}
      </body>
    </html>
  );
}
